### ISSUE TITLE
Yomichan not working on Google Docs 3/25/2022

### ISSUE THREAD

**Issue by grantf3** [FooSoft/yomichan#2094] opened 2022-03-26 02:32 UTC
**Description**
Before, Yomichan worked fine for me on Google Docs, and as of 3/25/2022 it's stopped working for some reason. It can scan kanji on other websites, but for some reason it stopped working for Google Docs. I've tried uninstalling and reinstalling dictionaries but that didn't work.

**Browser version**
Firefox 98.0.2

**Yomichan version**
22.2.2.0

**Comment by toasted-nutbread** [comment] 2022-03-26 16:23
Duplicate of #2093

**Closed** 2022-04-02 14:05 UTC
