### ISSUE TITLE
Yomichan Chrome extension isn't working with the android Kiwi Browser since version 20.5.22.0

### ISSUE THREAD

**Issue by Vikeo** [FooSoft/yomichan#595] opened 2020-06-08 03:40 UTC
Not sure if this is the best place to post this, but I'll try.

I've been using the Chromium based Kiwi Browser for the sole reason that Yomichan works excellent with it. But since 20.5.22.0 and 20.5.22.1 it stopped working. It turns on in the extension manager, but when I try to turn it on via the Yomichan On/Off button it always goes back to Off. If I go into the setting page the Active Profile box is empty, along with almost everything else, and no buttons work.
Version 20.4.10.1 and back still works fine, but since the extension automatically updates I can't use it for very long before it updates to the newest version. I've tried the latest update on 2 phones, but both were Samsung S10e.

That is all I know about this issue, I'm not 100% sure if it's not a Yomichan issue, but I ran out of ideas to try and get it fixed so now I wrote here.

**Comment by toasted-nutbread** [comment] 2020-06-08 22:57
Briefly testing myself, everything seems to work on Kiwi Browser 77.0.3865.92 and Yomichan 20.5.22.1 from the Chrome web store. Have you tried uninstalling the extension and reinstalling? How many dictionaries do you have installed?

**Comment by Vikeo** [comment] 2020-06-09 00:42
I've uninstalled and reinstalled the extension a few times, but the same thing happens everytime. I don't get the chance to install any dictionaries. To get to the Yomichan Options I have to go to the "Extensions" menu in the browser, press "Details" on Yomichan and then press "Extension options". But I can't install any dictionaries or change anything else while I'm in the options.

On version 20.4.10.1 I had the JMdict (Egnlish), KANJIDIC (English), JMnedict and Kanjium Pitch Accents dictionaries installed..

Don't know if it helps, but here's a video of how it looks. https://photos.app.goo.gl/KmjiPC99sy8wN6cw8

When I add the extension to chrome it says that the download fails, but it seems to install anyway. If If I download the 20.5.22.0 or 20.5.22.1 CRX file from another website and install that it seems to give the same result as installing from the chrome store.

**Comment by toasted-nutbread** [comment] 2020-06-09 02:53
You appear to be getting an error of some sort; it's quite hard to see, but the extension icon looks like it's showing this: ![image](https://user-images.githubusercontent.com/11037431/84100376-bfdab400-a9d9-11ea-931e-deacf02acd14.png). This would also explain why everything is not working. However, I cannot reproduce this error, and remote debugging the Kiwi browser is finicky. I can try to provide a custom build to help debug the error, and/or provide a description of how to try and debug the current version (which may only work if you have Windows 10). I basically just need a way to see what the logs are, but there doesn't seem to be a way to do so from inside the browser. I'll try to set that up soon.

**Comment by Vikeo** [comment] 2020-06-09 03:33
Ah yeah, completely missed that. 

My PC is running Win10. I don't know a whole lot about debugging but If I get some kind of instructions I think I can manage to get the logs. 
I appreciate the help!

**Comment by toasted-nutbread** [comment] 2020-06-09 22:41
Since the process to debug using what you currently have is more involved, let's try a debug release.

Package: [yomichan-20.5.22.1-with-logging-1.zip](https://github.com/FooSoft/yomichan/files/4755234/yomichan-20.5.22.1-with-logging-1.zip)
Source: https://github.com/toasted-nutbread/yomichan/commits/20.5.22.1-with-logging

So you should be able to put this file onto your device, and then installing it by enabling "Developer mode" on the extensions page, clicking the "Load" button, and selecting the .zip file.

On the settings page, even if it doesn't work, there should be a link at the very bottom that leads to a log page. This page should contain a textbox and two buttons for copying/selecting the text. The textbox should contain some info about errors that have been logged. If you can get to that and copy what's in there, that could be helpful.
![image](https://user-images.githubusercontent.com/11037431/84207541-9b391780-aa7f-11ea-9b72-494fe7b81e3d.png)
![image](https://user-images.githubusercontent.com/11037431/84208040-c53f0980-aa80-11ea-8492-c504c89fb7d9.png)

**Comment by Vikeo** [comment] 2020-06-10 00:02
Ok, here's the log.

https://pastebin.com/PTk9K3FD

**Comment by toasted-nutbread** [comment] 2020-06-10 00:21
Interesting. I think I know how to solve the issue; here is another testing build which logs some additional info and tries to avoid the issue. Try doing the same thing as before with this new version.

[yomichan-20.5.22.1-with-logging-2.zip](https://github.com/FooSoft/yomichan/files/4755490/yomichan-20.5.22.1-with-logging-2.zip)

**Comment by Vikeo** [comment] 2020-06-10 00:29
https://pastebin.com/xL0CNxRZ

Still getting the ![84100376-bfdab400-a9d9-11ea-931e-deacf02acd14](https://user-images.githubusercontent.com/66582202/84213871-c0b83680-aafc-11ea-9abd-612ac0b31b0b.png).

**Comment by toasted-nutbread** [comment] 2020-06-10 00:34
Whoops, forgot to handle the new case in some other code. Try this:
[yomichan-20.5.22.1-with-logging-3.zip](https://github.com/FooSoft/yomichan/files/4755535/yomichan-20.5.22.1-with-logging-3.zip)

**Comment by Vikeo** [comment] 2020-06-10 00:43
Now it works! Here's the the now now, just in case.
https://pastebin.com/h76rwW44

**Comment by toasted-nutbread** [comment] 2020-06-10 00:55
Great, thanks for your help as well. I'll make sure this issue gets fixed on the master release as well. If you're fine with using the working build from above, you can continue using that. Be aware that it probably won't automatically update.

**Comment by Vikeo** [comment] 2020-06-10 00:59
Yeah, I think I'll keep using this build for a little while and keep an eye out for the update then!

**Closed** 2020-06-10 04:01 UTC

**Comment by toasted-nutbread** [comment] 2020-06-28 15:20
FYI @Vikeo, the [dev version](https://chrome.google.com/webstore/detail/yomichan-development-buil/bcknnfebhefllbjhagijobjklocakpdm) has been updated with the latest fixes, and the standard version typically gets updated ~1 week after.
