### ISSUE TITLE
{clipboard-text-render-error} and {clipboard-image-render-error}

### ISSUE THREAD

**Issue by h10im** [FooSoft/yomichan#914] opened 2020-10-13 11:37 UTC
Using the anki integration, when I try to put the clipboard text or image onto a card field I get these two exceptions
for the handlebars ive got this 
https://pastebin.com/c77UZAgg

**Comment by toasted-nutbread** [comment] 2020-10-13 21:21
What browser are you on and what version of Yomichan do you have?

**Comment by h10im** [comment] 2020-10-14 08:09
Yomichan v20.9.28.0

**Comment by toasted-nutbread** [comment] 2020-10-14 21:43
This issue appears to be caused by the settings upgrade process not properly upgrading your templates. In your file, there are two declarations of `{{~> (lookup . "marker") ~}}`, where the upgrader expects only one.

If you have personally set up the templates and would like to keep the changes, you can do the following:
* Add the contents of this file: 
  https://github.com/FooSoft/yomichan/blob/20.9.28.0/ext/bg/data/anki-field-templates-upgrade-v4.handlebars
  above the _second_ occurrence of `{{~> (lookup . "marker") ~}}`. The first occurrence already had it added properly.

Otherwise, you can reset the templates to the default value on the settings page.

**Comment by h10im** [comment] 2020-10-15 05:11
I have added it and even tried resetting temple but this time it just shows up blank

**Comment by toasted-nutbread** [comment] 2020-10-15 22:07
Can you open up the settings page and toggle `Enable native popups when copying Japanese text` on, and then revert it to off? See if that makes it work.

I think the issue is the extension doesn't have the privilege to read the clipboard, so it needs to be requested. Toggling that option should request it.

That is a good point that it's very unclear that this is the case, and I overlooked it because my development version doesn't reset privileges. I'll work on an update to make this enabled properly.

**Comment by h10im** [comment] 2020-10-15 22:48
Toggling it asked me for the clipboard permissions and its now working, add be it takes while for when its for an image

**Comment by toasted-nutbread** [comment] 2020-10-15 23:37
> it takes while for when its for an image
This is mostly due to the image being added to Anki, which takes a bit to send the request + store the file I guess. Same thing happens for `{screenshot}` and `{audio}`.

Sounds like your issue is fixed using the workaround, so I'm going to close this and track the underlying issue using #925.

**Closed by toasted-nutbread** 2020-10-15 23:37 UTC

**Comment by Astarka06** [comment] 2022-08-24 16:12
> Enable native popups when copying Japanese text
can't find this option

**Comment by toasted-nutbread** [comment] 2022-08-24 22:50
The option mentioned in this issue is out of date, the updated label is _Enable background clipboard text monitoring_ in the _Clipboard_ section.

You can also now just check the permissions page and enable the `clipboardRead` permission. You can open the permissions page using the (?) button from the action popup, then clicking the _Permissions_ link at the bottom.
