### ISSUE TITLE
Anki doesn't add selected audio

### ISSUE THREAD

**Issue by Rapptz** [FooSoft/yomichan#1419] opened 2021-02-18 08:57 UTC
**Description**

When using the new multiple audio feature and then selecting an audio from the server (e.g. the server returns 4 pieces of audio and you access the one in index 2), Yomichan doesn't pass the selected audio to AnkiConnect, it always select the first index instead.

I wasn't sure if this was a bug or a feature request, but the behaviour was surprising to me. Going into a bit more detail, when you play audio it'll always try playing the first one that gets accessed. However, sometimes you want to select and have the corresponding card have audio from a different index.

If a sample payload from the custom server is required I can provide one if needed.

**Browser version**
Firefox 85.0.2

**Yomichan version**
Extension version: Yomichan 21.1.31.1
Platform: Windows
Browser: Firefox
Language: en-US
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0
AnkiConnect version: 6

**Comment by toasted-nutbread** [comment] 2021-02-18 22:41
Not a bug, it just wasn't implemented in the current release. It's since been implemented in the development version, but this is not released yet.

**Comment by toasted-nutbread** [comment] 2021-02-18 23:23
Also, just to clarify:

> Going into a bit more detail, when you play audio it'll always try playing the first one that gets accessed.

Is this the behaviour your expect, or would it somehow work differently? Since the menu opens instantly and the audio request is not sent until the audio is played (by clicking the speaker or a menu item), it doesn't know that there are multiple audio sources until that request has been made.

**Comment by Rapptz** [comment] 2021-02-19 03:18
> Not a bug, it just wasn't implemented in the current release. It's since been implemented in the development version, but this is not released yet.

Ah I see. I'm currently not using the development release since the .xpi aren't signed, though I could set it up Firefox Developer Edition to try it.

> Is this the behaviour your expect, or would it somehow work differently?

Playing the first selected audio makes sense to me, I can't see any other way to implement it. The user can already order the audio sources by priority. Likewise, the custom audio source server can also sort the array before sending it over. The surprising part to me was just the anki generation not respecting the selected audio. That caught me off guard.

**Comment by toasted-nutbread** [comment] 2021-02-19 03:22
> Ah I see. I'm currently not using the development release since the .xpi aren't signed, though I could set it up Firefox Developer Edition to try it.

It's not in the testing release yet either, its only committed to the repo.
![image](https://user-images.githubusercontent.com/11037431/108453113-cc393100-7237-11eb-9000-c67382e1e193.png)

**Comment by Rapptz** [comment] 2021-02-19 03:28
That looks fine. Though from that screenshot I'm unsure if those are two separate selectors, it seems like it. Is that to facilitate playing different audio and then selecting a different one for Anki?

**Comment by toasted-nutbread** [comment] 2021-02-19 03:39
When a sound is played from the menu, it is automatically selected for Anki cards (unless the audio wasn't found). This can be overridden by manually selecting which one for the cards, or deselected to use the default behaviour (going through the list of sources until one is valid).
![test](https://user-images.githubusercontent.com/11037431/108454160-dd833d00-7239-11eb-8e98-1cc2442c4029.gif)

**Comment by Thermospore** [comment] 2021-02-19 04:54
Oh snap how do you get Forvo hooked up? Not quite sure how to get the Forvo lookup as a JSON, do you have to use their api or something?

**Comment by toasted-nutbread** [comment] 2021-02-19 21:39
https://github.com/FooSoft/yomichan/issues/544#issuecomment-705769135

I am only using the example JSON.

**Closed** 2021-05-01 14:54 UTC
