### ISSUE TITLE
Database not initialized

### ISSUE THREAD

**Issue by adrianN** [FooSoft/yomichan#87] opened 2017-10-05 05:24 UTC
I installed Yomichan but I can't add any dictionaries. It says "Database not initialized" in a red box in the "Dictionary" section of the configuration screen. Restarting Firefox or purging the database doesnt' have any effect. I have also tried disabling all other addons and restarting Firefox. I'm on Firefox 56 on Mac OS and have Yomichan 1.4.0.

**Comment by FooSoft** [comment] 2017-10-05 19:50
Does using the [Refresh Firefox](https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings) help? Does removing and reinstalling the extension do anything?

**Comment by chibi4** [comment] 2017-10-05 20:15
Same issue for me. 
After refreshing Firefox yesterday, I was able to add dictionaries, but today it's showing me the very same error again. Removing and reinstalling does nothing. 
I can't believe that my profile is supposed to be corrupted within a day. I adjusted configuration via Firefox' options and only changed the openintab value in about:config. I have a few other add-ons and a theme installed, but disabling them doesn't change anything. I could send you my prefs.js if you think that would help. If I can get you any other info to help, do tell.
Thanks for your support!

**Comment by FooSoft** [comment] 2017-10-06 04:49
Just tried it on a 32-bit build of Firefox 56.0 on Windows 10, no repro so far. Will try 64 bit build tomorrow. Can either of you guys verify that IndexedDB is working at all on your setup by visiting the following page and clicking "Run" in the upper left corner?

https://jsfiddle.net/dfahlander/3tf5r0cu/

You should see
```
Using Dexie v2.0.1
Found friends: [
  {
    "name": "Foo",
    "age": 42,
    "id": 1
  }
]
```

appear in the bottom right pane.

**Comment by adrianN** [comment] 2017-10-06 05:19
I've found the source of the error. I use an extension for managing cookie permissions (Cookie Monster), which means that cookies aren't allowed ("Accept cookies from websites" is not checked). Apparently Firefox doesn't allow the use of IndexDB if cookies are disabled. [See this Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=748620). Enabling cookies fixes the error. 

However I would still like to use Yomichan without allowing every website to use local storage. I find it a bit weird that extensions fall under the same rules as websites. Maybe we could figure out in which context extensions run so that I can enable cookies selectively.

**Comment by FooSoft** [comment] 2017-10-06 05:46
Thank you for the update -- looks like there is another Firefox setting that can break IndexedDB without providing any feedback about the cause.

One would think that there is a which would allow extensions to execute without being impacted by other extensions or site settings. That is the way it works in Chrome at least. For extensions like Yomichan there are two contexts: the foreground page (where Yomichan injects the UI script into all pages), and the background script which is not exposed to the user and has access to more privileged APIs. I'm surprised that it is bound by the same limitations.

**Comment by chibi4** [comment] 2017-10-06 18:03
I had disabled cookies as well; enabling and keeping cookies until they expire fixed Yomichan for me too, though I had to restart Firefox for the change to really take effect. 

Putting Yomichan's extension URl "moz-extension://8e51eca5-3617-460c-ace9-13cef1a3d7ad/" into the whitelist allows me to run it with cookies disabled too.

I agree that extensions should be allowed out-of-box to access storage even if cookies are blocked, especially since they're asking for permission in their manifest - so user already confirm that for installation...

**Comment by FooSoft** [comment] 2017-10-07 00:35
@chibi4 that's a good idea, I'll update the documentation to tell people to do this. The extension URI is actually going to be different for each user, but you can get to it by using the search from the Yomichan browser button.

Closing this out, as there isn't anything I can do to make this work aside from letting people know about workarounds for the way Firefox deals with extensions.

**Closed by FooSoft** 2017-10-07 00:35 UTC
