### ISSUE TITLE
Yomichan no longer working in google docs' text

### ISSUE THREAD

**Issue by JackBD95** [FooSoft/yomichan#1971] opened 2021-09-30 08:50 UTC
**Description**
As it says in the title, started happening 2 days ago out of the blue, no other issues or changes. Works on the settings tabs etc. but doesn't work on the text within the word processing document

**Browser version**
chrome 93.0.4577.63 64bit

**Yomichan version**
Yomichan 21.8.31.1

**Comment by gadicc** [comment] 2021-09-30 15:45
Confirming this too.  I opened a Google Doc for the first time in a while 3 days ago (Mon 27th), hold down shift and move the mouse but no words are picked up / highlighted.  It's a Doc I've been using Yomichan in since May without problems, so must be a new Docs update I think.  Tested in Chrome and Firefox.

**Browser version**
Chrome 94.0.4606.61 (Official Build) (64-bit)
Firefox 92.0.1 (64-bit)

**Yomichan version**
Yomichan 21.8.31.1

**Comment by toasted-nutbread** [comment] 2021-09-30 23:08
Check the settings page, enable _Advanced_, _Accessibility_ > enable _Force HTML-based rendering for Google Docs_.

**Comment by gadicc** [comment] 2021-10-01 06:28
Hey @toasted-nutbread, thanks for the super quick answer.  This totally fixed things for me!  :tada:   Hope the same for OP.

**Comment by gadicc** [comment] 2021-10-01 06:41
Dupe of #1923, first mentioned in #1670 and fixed in #1875 (released in 21.8.31.0).

**Comment by JackBD95** [comment] 2021-10-01 08:57
thanks!!!

**Closed** 2021-10-01 22:00 UTC
