### ISSUE TITLE
Look up words inside yomichan's popup

### ISSUE THREAD

**Issue by baongoc124** [FooSoft/yomichan#139] opened 2018-10-02 05:57 UTC
I started to use monolingual dictionary and found that I need to look up the words inside definitions a lot. It would be very helpful if yomichan supports searching definitions of words inside the search results.

Thank you very much for a great piece of software!

**Comment by faneca** [comment] 2018-10-04 17:44
Related to (and possibly *duplicate of*) #75 (which maybe deserves a better title).

**Closed** 2019-08-04 02:54 UTC
