### ISSUE TITLE
Issue with scanning text with ruby Furigana tags

### ISSUE THREAD

**Issue by twicepipes** [FooSoft/yomichan#1504] opened 2021-03-08 18:21 UTC
**Description**
Words that contain Ruby furigana annotations sometimes cannot be scanned correctly. Each character of a word containing Ruby annotations is treated as its own separate entry. 

For example, if I try to scan the following word on a page:

<ruby>
<rb>短</rb>
 <rt>たん</rt>
 <rb>槍</rb>
 <rt>そう</rt>
</ruby>

If I hover over the left side, it highlights just 短, if I hover over the left, it highlights just 槍. It appears that the RT tags are being ignored, as I can't highlight the actual furigana themselves, but I'm also prevented from scanning this word to pull up a definition and create a card. 

https://github.com/FooSoft/yomichan/issues/30
https://github.com/FooSoft/yomichan/issues/50

I found these associated issues that seem to have been indicated as being fixed. I tried the examples on their Issue item and they work for me, so this appears to be a separate issue, probably due to the formatting of the Ruby tags. The way the above word (短槍) is formatted is the way that all furigana annotated words are formatted in Kindle books. 

**Browser version**
Chrome 88.0.4324.190 

**Yomichan version**
21.1.31.1

**Exported settings file**
[yomichan-settings-2021-03-08-18-15-28.txt](https://github.com/FooSoft/yomichan/files/6103322/yomichan-settings-2021-03-08-18-15-28.txt)

**Comment by toasted-nutbread** [comment] 2021-03-08 22:33
There is a space between the kanji, which is terminating the words. i.e. Yomichan is seeing `短 槍` instead of `短槍`. Another example: `漢 字` vs `漢字`. This is the expected behaviour.

The furigana is ignored as you mention, and this is also the expected behaviour.

If you are using Yomichan on content that is formatted in this way, you could try setting up a text replacement pattern to remove whitespace. To do this, open the settings page, enable _Advanced_, go to the _Translation_ section, and click the _Configure custom text replacement patterns…_ button. In there, add a new replacement pattern where the pattern is `\s+` and the replacement is empty. This should remove whitespace characters from parsed text. Depending on how many characters are typically removed, you may have to increase the value of the _Text scan length_ option (under _Scanning_).

**Comment by twicepipes** [comment] 2021-03-08 23:55
> There is a space between the kanji, which is terminating the words. i.e. Yomichan is seeing `短 槍` instead of `短槍`. Another example: `漢 字` vs `漢字`. This is the expected behaviour.
> 
> The furigana is ignored as you mention, and this is also the expected behaviour.
> 
> If you are using Yomichan on content that is formatted in this way, you could try setting up a text replacement pattern to remove whitespace. To do this, open the settings page, enable _Advanced_, go to the _Translation_ section, and click the _Configure custom text replacement patterns…_ button. In there, add a new replacement pattern where the pattern is `\s+` and the replacement is empty. This should remove whitespace characters from parsed text. Depending on how many characters are typically removed, you may have to increase the value of the _Text scan length_ option (under _Scanning_).

Excellent, that did exactly what I wanted. I did notice that when I removed the RT tags with the Chrome inspection tool that a space would be left behind and knew that was probably the culprit, but I wasn't aware there was already a way within the Yomichan options to address that. Thanks a bunch. By the way, is there a way through keyboard shortcuts to quickly enable and disable that replacement pattern?

**Comment by toasted-nutbread** [comment] 2021-03-09 01:28
> By the way, is there a way through keyboard shortcuts to quickly enable and disable that replacement pattern?

Currently no, although a similar feature has been requested here: #1416. The current alternative is to set up a second profile, but that is sometimes overkill for some needs.

**Comment by toasted-nutbread** [comment] 2021-03-28 17:37
#1571 adds a hotkey action for toggling a specific option.

**Comment by weirdalsuperfan** [comment] 2021-04-27 11:34
I'm trying to use yomichan's clipboard monitoring to pop up the search window when Capture2Text OCR's something, but Capture2Text keeps returning the text with whitespace between each character. I tried adding \s+ as a custom text replacement pattern (I also have other non-custom patterns enabled), but no matter what text I copy, even if I write it out and then copy it myself, it only searches the original text (i.e. only shows results for individual characters).

Closing the search window doesn't help, although I haven't tried restarting my browser yet. Is there something extra I need to do to get this to work in the search window? Does the search window/clipboard monitor not go through these custom replacement patterns? It seems to still use the other replacement patterns.

Since capture2text lets you send the text to another application, I suppose I could just write a script that will receive the text and use that to remove whitespace for me before re-copying to update the search window, but I'm already using capture2text's executable functionality for something else.

**Comment by weirdalsuperfan** [comment] 2021-04-27 12:02
Solution: Search text with non-Japanese characters must be turned on or the replacement text being blank or punctuation, etc., will cause the pattern to not do anything. This is pretty suboptimal though, since I prefer to always have that setting switched off.

**Comment by toasted-nutbread** [comment] 2021-04-29 01:16
This is the expected behaviour. I haven't looked into this, but maybe I could add a way to use a specific settings profile when using clipboard monitoring, rather than the default?

**Comment by toasted-nutbread** [comment] 2021-05-01 14:53
Closing this issue since the main request was resolved.

**Closed by toasted-nutbread** 2021-05-01 14:53 UTC
