### ISSUE TITLE
Is there a way to add all the text in the preview and not just the sentence

### ISSUE THREAD

**Issue by TingTingin** [FooSoft/yomichan#1680] opened 2021-05-16 00:39 UTC
If I try to add a word from this screen it will add the sentence its in with {sentence}

![brave_oy0nCRVMMT](https://user-images.githubusercontent.com/36141041/118381800-c2b43080-b5bc-11eb-8cba-12c355179628.png)

But I want to add all the text in the preview and not have the sentence bounds stop at new lines the text comes like this when I use OCR in mangas and I wanna avoid having to put all the text in one line

**Comment by toasted-nutbread** [comment] 2021-05-16 01:18
You can set up a second profile with a condition to activate it on the settings page, and then disable the sentence termination character checks and increase sentence extents.

**Comment by TingTingin** [comment] 2021-05-16 01:46
If I turn of sentence termination it still stops at newlines is that intended behaviour?

**Comment by toasted-nutbread** [comment] 2021-05-16 02:23
You're right, I forgot about newlines. That's currently the intended behaviour; I would have to reconfigure some settings to allow for ignoring newlines.

**Comment by TingTingin** [comment] 2021-05-16 03:14
kk thx I was wondering if I was doing something wrong thx for the help

**Comment by TingTingin** [comment] 2021-05-17 22:25
I tried the recent change and it works however when used in the popup it now even goes as far as matching all the words in the UI this is example output from this sentence

家族と共に 
豊かで安全な生活が 
保障されることに 
なっているのです 生活

`Yomichan Search Automatic kana conversion Clipboard monitor 家族と共に 豊かで安全な生活が 保障されることに なっているのです 生活 P ichi news Innocent Corpus 54668 Kanjium Pitch Accents せいかつ0 P n vs KireiCake living life (one`

the matching goes even as far as matching the ui text ive worked around this by encasing the text in termination characters like so

`!家族と共に 
豊かで安全な生活が 
保障されることに 
なっているのです 生活!`

in that case yomichan stops matching at those and only matches the sentence but was wondering if there is a more permanent solution 

also as a side bar now that newlines can be matched it seems than when adding the card to anki they dont get preserved but instead all go on one line dont know if this is intended

**Comment by toasted-nutbread** [comment] 2021-05-18 00:18
You're right, my workaround was a bit of a hack, so I've implemented it (hopefully) properly in #1686. There is now a new `{search-query}` marker.

> also as a side bar now that newlines can be matched it seems than when adding the card to anki they dont get preserved but instead all go on one line dont know if this is intended

That's probably a presentation issue which could be fixed by wrapping the template content in `{{#multiLine}}...{{/multiLine}}`.

**Closed** 2021-05-18 00:18 UTC
