### ISSUE TITLE
crash in google docs

### ISSUE THREAD

**Issue by KudouUsagi** [FooSoft/yomichan#659] opened 2020-07-10 04:57 UTC
Whenever I use yomichan on google docs recently google docs crashes and reloads the page. I use firefox.

**Comment by toasted-nutbread** [comment] 2020-07-10 17:31
What version of Yomichan are you on? What triggers the reload?

This may be related to #608, which has been fixed in the testing release, but hasn't been promoted to a stable release yet.

**Comment by KudouUsagi** [comment] 2020-07-10 21:28
I'm using version 20.5.22.1 of yomichan. It usually happens when it pulls up a pop up.

**Comment by toasted-nutbread** [comment] 2020-07-10 22:12
I'm attempting to reproduce that version and so far not having the issue; I wasn't able to reproduce the issue someone else had with Google Docs either. Few more questions:
* What version of Firefox?
* Do you have any other extensions installed?
* What dictionaries do you have installed?
* Can you export your settings file and share it here?

**Comment by KudouUsagi** [comment] 2020-07-10 22:21
firefox version: 78.0.1 (64-bit)
![image](https://user-images.githubusercontent.com/40532852/87207408-711e8380-c2d1-11ea-95e5-e58ad7ede2a0.png)
![image](https://user-images.githubusercontent.com/40532852/87207251-1edd6280-c2d1-11ea-9054-bc7ac6d8f6fd.png)
https://www.mediafire.com/file/agnbwfwhfwftqro/yomichan-settings-2020-07-10-22-19-34.json/file

**Comment by toasted-nutbread** [comment] 2020-07-10 23:22
Does this happen on every document, or only specific documents/content? If specific, can you export a copy in docx format to share? Or if it's all documents, does it matter what the complexity of the document is? E.g. if it's a single character, will it crash? Or is there a certain amount of characters required?

@FooSoft, since this may be the same issue that #608 was having, we may need to bump the latest testing release to stable to see if that fixes the issue.

**Comment by FooSoft** [comment] 2020-07-10 23:32
Sounds good, was just think it migh be good time to promote testing :)

**Comment by KudouUsagi** [comment] 2020-07-11 00:02
It has happened in multiple docs and doesn't seem to matter how complex. Sometimes it will work for a few look ups and sometimes it crashes on the first one.

**Comment by toasted-nutbread** [comment] 2020-07-20 01:43
@KudouUsagi The most recent release of Yomichan is now 20.6.27.2; see if updating fixes your issue with Google Docs.

**Comment by KudouUsagi** [comment] 2020-07-20 01:48
It does seem to have fixed it! It hasn't crashed since it updated.

**Comment by toasted-nutbread** [comment] 2020-07-20 02:04
Great, hopefully it continues to work! In case you run into any more problems, feel free to open a new issue.

**Closed by toasted-nutbread** 2020-07-20 02:04 UTC
