### ISSUE TITLE
(feature request) Pitch accents.

### ISSUE THREAD

**Issue by juggler12345** [FooSoft/yomichan#131] opened 2018-08-01 11:50 UTC
I know this has already been requested about a year ago, but I was wondering whether pitch accent would be able to be added as a feature?
I use yomichan everyday, but frequently have to look up pitch accents and was thinking how good it would be to have everything all in one place!
Many thanks for creating an amazing add-on :)

**Comment by faneca** [comment] 2018-10-04 17:35
As you mention, this is a duplicate of #61. I've answered [there](https://github.com/FooSoft/yomichan/issues/61#issuecomment-427104256) with a hack; hope that @FooSoft implements something better in the future ;-).

**Comment by grenzionky** [comment] 2019-03-29 00:29
https://www.youtube.com/watch?v=5oxdPY9eH48
download the zip and add nhk pitch accent file 
[heres the direct link to the nhk accent dictionary](https://mega.nz/#!45dGDAbJ!SvwFC7Q2jRPfyyJl4dgc61IICLldxTF3IAIfiKxN0gc)

**Comment by toasted-nutbread** [comment] 2020-02-08 22:09
Closing this issue as a duplicate. Development discussion can be found in #61.

**Closed by toasted-nutbread** 2020-02-08 22:09 UTC
Labels: duplicate, enhancement
