### ISSUE TITLE
Technical documentation

### ISSUE THREAD

**Issue by siikamiika** [FooSoft/yomichan#403] opened 2020-03-08 14:20 UTC
There has already been some comments and discussion about this such as https://github.com/FooSoft/yomichan/issues/322, but I'll open it as a new issue for better tracking.

I think the project is becoming so large that it would help new developers and our future selves if we documented the core components and their relationships so that it can be referenced while reading the source code and discussing the addition of new features.

The structure is already pretty good and consistent, but there are many hops between moving the mouse cursor and getting the results to display, not to mention in a second popup created by scanning the first.

This is somewhat related to https://github.com/FooSoft/yomichan/issues/356, as it would help to conclude when it's done. I think there could still be some work to do on the `Popup*` classes because they don't have a prepare method.

I don't have a strong opinion or even experience of choosing an appropriate tool for doing this, but I think it should be something that can indicate the entry points and flow of messages when some core feature events such as text scanning happen. In my opinion the code itself is good documentation for the internal functionality of the components, but some of them could maybe have a general comment about what they do.

**Comment by toasted-nutbread** [comment] 2020-03-08 15:52
My hopes are that a lot of documentation can be implicit by having the code be well structured and organized. For example, converting certain groups of functions to classes or module-like objects (#372) and marking internals as private (#258). In my opinion, this will go a long way, particularly for someone who is code savvy and knows how to scan through a codebase.

My intent with the JSON schemas has been that they are self-documenting for anyone who knows how to read them. This is why I have added the `description` fields which are otherwise not used in the code. I realize that it can't be assumed that everyone will already understand the schema format (i.e. less technical users who still understand basic JSON), but it can also help us to guide users correctly if it comes up (#382).

For high-level documentation on components, their relationships, design practices, etc., the wiki page is an option: https://github.com/FooSoft/yomichan/wiki. An alternative is creating a "docs" folder in the root project containing markdown files.

For more internal comments, [doc comments](https://jsdoc.app/about-getting-started.html) are certainly an option. I think there are tools to automatically compile doc comments to API HTML documentation pages, but personally I am usually satisfied to just read the comments inline in the code when I need them, since it's usually part of the development workflow anyway to look at a function's declaration.

For internal comments, usually private members aren't documented. Doc comments could be added to existing components on an on-demand basis, or whenever it's otherwise convenient to have additional info. For new classes, maybe minimally just adding a doc comment about what the class does could be helpful.

**Comment by FooSoft** [comment] 2020-03-10 00:27
Documentation can be great to have, but the problem is that it has to be kept up to date... the only thing that is worse than no documentation is incorrect documentation. Considering how many structural changes are happening in the project, said documentation would likely get out of date pretty quickly. Perhaps some sort of auto-generated documentation approach would work? Not sure if this is an option for JavaScript, considering just how dynamic the language is.

**Comment by toasted-nutbread** [comment] 2020-08-01 20:39
I am going to close this issue for now, since it's not tracking a specific change that should occur, and some of the comments have been addressed. In general, documentation of some form that is helpful to users of Yomichan is something that should be worked towards, even if it's something such as a JSON schema. In #703, I have documented the Handlebars helper functions that are available, so that falls under that category.

In terms of documenting the codebase, the most effective thing to do would be to add JavaScript doc comments inline. Some files already have this, such as [`DOMTextScanner`](https://github.com/FooSoft/yomichan/blob/f7df6254d6f71d5331b000dcbd27271bd2c3006f/ext/fg/js/dom-text-scanner.js), and it may be a good idea to do this for newly created classes as well (although in practice this may not always happen).

In general, demand for information will help to drive these things.

**Closed by toasted-nutbread** 2020-08-01 20:39 UTC
Labels: discussion
