### ISSUE TITLE
Template render error in Firefox

### ISSUE THREAD

**Issue by man1001** [FooSoft/yomichan#1823] opened 2021-07-11 14:59 UTC
When I try to create a Anki Card with yomichan I get the Error-Message:
8 errors occurred:

    Template render error for {expression}
    Template render error for {reading}
    Template render error for {glossary}
    Template render error for {audio}
    Template render error for {sentence}
    Template render error for {furigana}
    Template render error for {screenshot}
    Template render error for {conjugation}

I disabled all other extensions but that didnt help.
In Chrome it still works with the same imported configuration.

Extension version: Yomichan 21.6.30.0
Platform: Windows
Browser: Firefox 89.0.2 
Language: de
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
AnkiConnect version: 6

**Comment by Thermospore** [comment] 2021-07-11 15:01
Should be fixed in 21.6.30.2

**Comment by toasted-nutbread** [comment] 2021-07-11 15:03
Duplicate of #1821

**Closed** 2021-07-11 15:09 UTC

**Comment by man1001** [comment] 2021-07-11 15:11
Upateding to 21.6.30.2 fixed the error, sorry for the duplicate.
