### ISSUE TITLE
Change back or add option for previous style frequency value

### ISSUE THREAD

**Issue by shoui520** [FooSoft/yomichan#1409] opened 2021-02-16 14:05 UTC
In the new Yomichan update, the frequency value is displayed outside of the tag.
![brave_LfWF4nYMoR](https://user-images.githubusercontent.com/77593657/108072983-77db5900-705f-11eb-9ddc-14777daaf674.png)  

Can this change be reverted or be changed in the options?

**Comment by shoui520** [comment] 2021-02-16 15:31
I have made a temporary fix using CSS. 

https://learnjapanese.moe/yomicss/#frequency-value-outside-of-tag

**Comment by wwly23** [comment] 2021-02-16 18:16
This bothers me a lot more than it should. It just draws my eyes to 1000% pointless text that takes up two lines of limited popup space on what should be a compact number to reference.

**Comment by Thermospore** [comment] 2021-02-16 19:52
Eh I think as humans we are just really resistant to change, especially in UI

btw that dictionary literally put a `:` in its title, which you can just remove

in compact mode everything is on one line:
![image](https://user-images.githubusercontent.com/35350819/108110680-13f56800-7040-11eb-943d-8bd4e2fd001c.png)

The new design drastically improves readability and compactness of freq info in merged mode (see #1093):

old:
![image](https://user-images.githubusercontent.com/35350819/102687591-9676be00-419c-11eb-8fa0-38b530466d9a.png)

new:
![image](https://user-images.githubusercontent.com/35350819/108113047-6dab6180-7043-11eb-8a75-dfbc80e1b1ca.png)

You should really try out merged mode btw, I don't think I could ever go back. I recommend using jmdict as the primary/pivot dictionary (even if you usually read a monolingual one) since it includes just about every form you can imagine, so makes it way more likely that your word will get pulled up

For example I was able to look up `色々` and still get the definition in 新明解国語辞典 even though it writes it as `色色`
![image](https://user-images.githubusercontent.com/35350819/108113681-44d79c00-7044-11eb-9de7-b8b07ca44d78.png)

**Comment by FirionHope** [comment] 2021-02-16 22:42
Can we get an option to get rid of where it says "frequencies" and "definitions" like before? I know which is the frequency and which is the definitions, adding extra lines for it just makes it pointlessly take up space

**Comment by toasted-nutbread** [comment] 2021-02-17 00:17
The rationale behind the headers is that it is not inherently clear what the different groupings are, or why some have list numbers/dots and some do not.

Example without the headings:
![image](https://user-images.githubusercontent.com/11037431/108137007-07493200-7089-11eb-979d-b59afa99da10.png)

Unclear or inconsistent why there are sometimes numberings and sometimes not. If numbers are included for every item, there will be repeats (1. 2. 1. 1. 2. 3. ...)

This is not to say the "solution" is optimal, but the change is not unmotivated. I will look into addressing this in a more concise manner.

---

The separation of the dictionary tag from the content has to do with information density and stylistic consistency.
* All other dictionary tags are separate from what they are annotating.
* Having disambiguation information inside the tag greatly bloats the size of the tag and is not consistent with the other disambiguation styles, e.g. `(ああ only)`.
* There may be other information added in the future which would further bloat the tags. For example, at some point, there may need to be a way to disambiguate frequencies representing # of occurrences (higher = more frequent) vs ranking (lower = more frequent).

So the issue is that this "number" is not necessary able to be compactly represented in all display modes.

---

Addressing random issues from https://learnjapanese.moe/yomicss:

> Ctrl+C / ⌘+C not working

Now fixed in #1411.

> Removing current entry indicator

There is a setting to change this: _Selection indicator style_.

---

@FirionHope For now, set up custom CSS rule:
```css
h5 { display: none; }
```

**Comment by Thermospore** [comment] 2021-02-17 00:37
@FirionHope 
> Can we get an option to get rid of where it says "frequencies" and "definitions" like before? I know which is the frequency and which is the definitions, adding extra lines for it just makes it pointlessly take up space

You might like `Compact glossaries`
![image](https://user-images.githubusercontent.com/35350819/108139325-57fe6200-706c-11eb-821a-74cb15070467.png)

**Comment by Thermospore** [comment] 2021-02-17 00:42
> Addressing random issues from https://learnjapanese.moe/yomicss:

I feel like they spent more time writing CSS than looking at the settings page haha

Also it appears they haven't discovered merged mode yet... poor souls

**Comment by FirionHope** [comment] 2021-02-17 00:46
Well thing is for me I only have 1 corpus and 1 dict installed so I don't run into the problem you mention whereas my experience (just slightly I'll admit) suffers with the change, though I see where you're coming from with it. Thank you for the custom CSS.

I just gave compact glossaries a shot too, thats a very nice option though I prefer how it looks normally aside from the new lines. I'll switch to it if the custom CSS stops working, thanks.

**Comment by toasted-nutbread** [comment] 2021-02-17 00:53
> You might like Compact glossaries

That does have other effects, though removing headings is one of them.

> I feel like they spent more time writing CSS than looking at the settings page

To be fair, the settings page has changed dramatically, and I don't fault people for assuming there may not be options for some of the style changes (such as the selection indicator).

And merged mode may not be optimal for all workflows, it might not be what everyone wants in Anki cards for example. Additionally, I assume it's a rare case, but using merged mode on devices with a touch screen is also more difficult to view all info, due to certain functionality requiring pointer hovering.

> Well thing is for me I only have 1 corpus and 1 dict installed so I don't run into the problem you mention whereas my experience (just slightly I'll admit) suffers with the change, though I see where you're coming from with it. Thank you for the custom CSS.

It's good to know when changes negatively affect user experience, so thanks for reporting.

**Comment by Thermospore** [comment] 2021-02-17 01:00
> To be fair, the settings page has changed dramatically, and I don't fault people for assuming there may not be options for some of the style changes (such as the selection indicator).

Hmmm maybe there could be something to draw attention to newly added settings so people don't miss them. Like a red `new` tag or something

**Comment by seanblue** [comment] 2021-02-17 01:35
I would also like to get rid of the new headers. I only have one pitch accent dictionary and one frequency dictionary. I know which is which by name (and color) and don't need headers for that. It just makes it take up more space. I just tried "compact glossaries" as suggested, but I don't like the other changes that makes.

I also preferred the numbers being inside the tags. Maybe it's just me, but I think having numbers floating around in plaintext clashes with the aesthetics of the extension.

**Comment by Thermospore** [comment] 2021-02-17 02:35
> Maybe it's just me, but I think having numbers floating around in plaintext clashes with the aesthetics of the extension.

I thought it was kinda off at first as well, but I think it was just a resistance to change thing. It's only been a day and the new way already looks better to me, fwiw. Not to mention the reasons listed above (search `The separation of the dictionary tag from the content has to do with information density and stylistic consistency`)

this looks pretty slick if you ask me (this is merged mode + compact mode btw)
![image](https://user-images.githubusercontent.com/35350819/108148278-f72b5580-707c-11eb-9a63-3cfb7febaba1.png)
maybe the `news` tag could be bumped up to the `深淵` line, but that's all that jumps out at me

**Comment by seanblue** [comment] 2021-02-17 02:43
@Thermospore Here is mine for comparison:

![image](https://user-images.githubusercontent.com/5884067/108148901-c3adf280-709f-11eb-9f73-ba899207f9eb.png)

---
I'm much less concerned about the plaintext numbers than the headers though. As you can see from the image above, the headers add a significant amount of (wasted) vertical space.

**Comment by toasted-nutbread** [comment] 2021-02-17 02:47
I've set up patch release [21.1.31.1](https://github.com/FooSoft/yomichan/releases/tag/21.1.31.1) to address the initial concerns with the headings (and some other issues) and I'll continue to work on other tag display improvements. I may post some options here to see if anyone has any thoughts, so please wait warmly.

**Comment by Thermospore** [comment] 2021-02-17 03:02
> @Thermospore Here is mine for comparison:

hmm yeah I agree, even for non-compact mode that's a bit much

gotta avoid this though, not sure what the best way would be
![image](https://user-images.githubusercontent.com/35350819/108149918-3909cb00-7080-11eb-8ac3-0e27b0d5bc99.png)

maybe a bit of space + a little line could get the job done?
![image](https://user-images.githubusercontent.com/35350819/108150244-d6fd9580-7080-11eb-8285-49982ffdb2a8.png)

**Comment by toasted-nutbread** [comment] 2021-02-18 02:27
Here is a mock-up of a potential solution to the frequency tag issue, zoomed 200% for clarity. On top, there are some of the more complex listings, and on bottom are the simple versions. This is by no means final, but looking for feedback as to whether this would be more in the right direction.

![image](https://user-images.githubusercontent.com/11037431/108295917-924c2a00-7166-11eb-8c3a-9202e407358c.png)

**Comment by seanblue** [comment] 2021-02-18 02:47
@toasted-nutbread I think the green boarder is a nice middle ground between the old and current versions. Can you show what it would look like with "Compact glossaries" turned off?

**Comment by toasted-nutbread** [comment] 2021-02-18 03:25
It's very broken based on the CSS I threw together, but I can work on setting it up soon.

**Comment by Thermospore** [comment] 2021-02-18 04:49
Hmm the border is an interesting idea, but I don't really feel the need for it. Doesn't seem consistent with the rest of the design either. Maybe it would grow on me

I think I prefer the current borderless + `|`  the most, which is what the other sections do in `Compact glossaries` mode
![image](https://user-images.githubusercontent.com/35350819/108305375-4ee9bf80-7156-11eb-86e3-1cfa459ab558.png)

Seems like people are most concerned with how the numbering / section separation when not in `Compact glossaries` mode will be handled tho

man UI design has gotta be hard, especially with so many different use cases and option configs...

**Comment by toasted-nutbread** [comment] 2021-02-24 23:23
For all in this thread, I've created some new options to control how frequency information is displayed. Hopefully these should satisfy most of the requests here.

1. [tags](https://user-images.githubusercontent.com/11037431/109079045-58ca7000-76cc-11eb-86f8-44335e13b05a.png) (old style)
2. [tags-grouped](https://user-images.githubusercontent.com/11037431/109079086-6849b900-76cc-11eb-99ad-ee6272c19b43.png) (new)
3. [split-tags](https://user-images.githubusercontent.com/11037431/109079106-71d32100-76cc-11eb-9659-fbecffb00112.png) (new)
4. [split-tags-grouped](https://user-images.githubusercontent.com/11037431/109079128-7b5c8900-76cc-11eb-9ced-165489468481.png) (new, default)
5. [inline-list](https://user-images.githubusercontent.com/11037431/109079153-84e5f100-76cc-11eb-9f9a-50e6651126b3.png) (current style, compact layout)
6. [list](https://user-images.githubusercontent.com/11037431/109079180-8dd6c280-76cc-11eb-84a3-b1875f641ada.png) (current style, non-compact layout)

Note: when the setting _Result grouping mode_ is not _Group related terms_, the grouped modes are the same as the ungrouped modes. The grouped modes are intended to provide a more compact display for frequencies of multiple expressions.

**Comment by Thermospore** [comment] 2021-02-25 04:21
Works for me! Yeah I don't think it would have been possible to make everyone happy with a single style

Ooo is the frequency info sorted now, or is that just a coincidence?

I'm thinking there are two possible directions to go for how to present options for frequency info styling. One is to give a list of presets (which is the direction taken in #1438). The other would be to present the styling choices individually, as in something like:
- tag style: block, pill, header (like in presets 1&2, 3&4, 5&6 respectively)
- grouping: none, by freq dictionary, by surface form (like in presets 1&3, 2&4-6, [doesn't currently exist] respectively)
- line spacing: inline, list (like in presets 1-5, 6 respectively)

`tag style` would probably be a sub-option of `line spacing`, since it would only be relevant for the `inline` style

I wonder which approach people would prefer? Maybe the three options would be more straightforward, I dunno

**Comment by toasted-nutbread** [comment] 2021-02-25 22:44
For simplicity, it's just set up as a dropdown. The view on the right side is live, so that should give enough clarity on how it looks.

![image](https://user-images.githubusercontent.com/11037431/109229159-e8395700-7790-11eb-8031-27af8e00ada3.gif)

**Comment by toasted-nutbread** [comment] 2021-03-13 20:16
Options have been added in the latest 21.2 release.

**Closed by toasted-nutbread** 2021-03-13 20:16 UTC
