### ISSUE TITLE
Popup window no longer shows up on Firefox 71.0 on Linux

### ISSUE THREAD

**Issue by gestra** [FooSoft/yomichan#298] opened 2019-12-05 12:59 UTC
After updating to Firefox 71.0 on Fedora 31 I no longer get the popup window. Two types of error are printed in console when trying different words on a page:

```
Yomichan v1.8.8 has encountered an error.
Originating URL: https://jisho.org/word/%E5%A3%8A%E3%82%8C%E3%82%8B
TypeError: definitions is undefined
searchKanji@moz-extension://e17f523a-24bd-49e0-82ea-6b8b5ccd9fa7/fg/js/frontend.js:385:13

Issues can be reported at https://github.com/FooSoft/yomichan/issues extension.js:82:13
```
and
```
Yomichan v1.8.8 has encountered an error.
Originating URL: https://jisho.org/word/%E5%A3%8A%E3%82%8C%E3%82%8B
TypeError: undefined has no properties
searchTerms@moz-extension://e17f523a-24bd-49e0-82ea-6b8b5ccd9fa7/fg/js/frontend.js:351:45

Issues can be reported at https://github.com/FooSoft/yomichan/issues 3 extension.js:82:13
```

**Comment by gestra** [comment] 2019-12-05 13:37
Actually it seems like this might be an issue with Fedora's Firefox build instead. Yomichan works fine with Mozilla's official build and multiple people have reported broken extensions on Fedora's Firefox 71:
https://bugzilla.redhat.com/show_bug.cgi?id=1779570
https://bugzilla.redhat.com/show_bug.cgi?id=1779762
https://github.com/keepassxreboot/keepassxc-browser/issues/704

**Comment by siikamiika** [comment] 2019-12-05 17:33
@gestra Thanks for the great bug report and research! It makes sense that `definitions` would be undefined if IndexedDB doesn't work. I'll close the issue.

**Comment by jonascarpay** [comment] 2019-12-08 05:24
Are you sure that this is an external issue? I'm seeing `TypeError: undefined has no properties` on FF71 on NixOS as well.
  - Nix uses a pretty stock Firefox, and there are no reports of other plugins breaking
  - The `testing` branch of YomiChan does not have this issue

**Comment by siikamiika** [comment] 2019-12-08 09:46
@jonascarpay 
I'll reopen and re-tag the issue until we figure out what's causing it, but Firefox 71 still seems to be in common with both of you. The information that this doesn't happen on the testing branch is potentially very valuable.

Meanwhile, can you test if this returns any errors? https://firefox-storage-test.glitch.me/

**Comment by jonascarpay** [comment] 2019-12-08 10:08
All green on both FF70 and FF71:
```
Overview:
Storage is working. You upgraded from 70 to 71.
Specific Subsystem Statuses:

LocalStorage
    Good: Totally Working. (fullyOperational)
QuotaManager
    Good: Totally Working. (fullyOperational)
IndexedDB
    Good: Totally Working. (fullyOperational)
Cache API
    Good: Totally Working. (fullyOperational)

Debug Info:

{
  "v": 1,
  "curVersion": 71,
  "prevVersion": 70,
  "ls": {},
  "qm": {
    "lastWorkedIn": 71
  },
  "idb": {
    "persistentCreatedIn": 70,
    "persistentLastOpenedIn": 71,
    "clearDetectedIn": 0
  },
  "cache": {
    "firstCacheCreatedIn": 0,
    "unpaddedOpaqueCreatedIn": 0,
    "paddedOpaqueCreatedIn": 71
  }
}
```

**Comment by gestra** [comment] 2019-12-08 10:09
Debian's Firefox 71 builds also break extensions so that is not limited to Fedora:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=946249

Personally I just downgraded to Firefox 70 for the time being.

**Comment by siikamiika** [comment] 2019-12-08 10:56
One possible reason for Yomichan working on testing but not on stable is that Firefox 71 might have broken existing IndexedDB storage but still work when it's created from scratch. @jonascarpay can you test creating a new profile on Firefox 71 and installing Yomichan stable?

**Comment by jonascarpay** [comment] 2019-12-08 11:36
Same error, `TypeError: undefined has no properties`. However, I tried on a Windows VM and there it works fine on FF71.

**Comment by siikamiika** [comment] 2019-12-08 12:10
One thing related to the database that has happened between 1.8.8 stable and current master is the removal of [Dexie](https://dexie.org/) in https://github.com/FooSoft/yomichan/pull/278. Dexie could be doing something that certain versions of Firefox 71 doesn't like.

**Comment by siikamiika** [comment] 2019-12-08 22:03
I have found the commit that fixed Firefox 71 on Fedora and others: https://github.com/FooSoft/yomichan/commit/96e4bf1735cef3881e5284ff624ed2114709af82. It was indeed caused by Dexie doing something that breaks the faulty database engine.

While bisecting, I also found that dictionary importing has given an error message on Firefox 71 (but not on Chrome) until this commit https://github.com/FooSoft/yomichan/commit/db4a30336595eca94e976b6279c1e8c79df85906.

**Comment by siikamiika** [comment] 2019-12-08 22:09
@FooSoft do you think Firefox needs a new release with https://github.com/FooSoft/yomichan/commit/96e4bf1735cef3881e5284ff624ed2114709af82 cherry-picked or should we wait for them to sort it out? Some new features on master probably need more testing before release. The error message fixed by https://github.com/FooSoft/yomichan/commit/db4a30336595eca94e976b6279c1e8c79df85906 wasn't fatal.

**Comment by FooSoft** [comment] 2019-12-09 02:09
It probably just makes sense to drop master directly into testing, assuming all of the known issues are resolved. Thanks to you and @toasted-nutbread this project has really high velocity now, so when doing a testing release, it probably just makes sense to test everything else that came after that as well.

**Comment by siikamiika** [comment] 2019-12-09 17:34
Alright :+1: So as a conclusion, use the testing release at https://foosoft.net/projects/yomichan/index.html#installation until Firefox is fixed.

**Closed by siikamiika** 2019-12-09 17:34 UTC
Labels: not our bug

**Comment by toasted-nutbread** [comment] 2019-12-23 00:11
Interesting side note: it looks like Rikaichamp also recently had a similar issue with dexie/indexedDB: https://github.com/birtles/rikaichamp/issues/148
