### ISSUE TITLE
Can make term cards but not kanji cards for anki

### ISSUE THREAD

**Issue by nammerduong** [FooSoft/yomichan#1071] opened 2020-11-27 18:25 UTC
Literally like 1-2 days ago I was able to make kanji cards fine. I'm not sure what changed since then since I'm pretty sure yomichan and anki didn't have updates. All I really changed in that period was change the handlebar template but I've put it back to default and it still wont create kanji cards. Yomichan would show an error on it's icon but won't explain what the error is when I try to create a kanji card. I've tried reinstalling yomichan and putting the settings back to default to no avail. I mainly use chrome but I also tried yomichan on firefox and had the same problem. To be more specific the green button isn't grayed out, but when I press it, nothing happens and yomichan's icon displays an error.

yomichan displaying an error:
![iXOQhIu](https://user-images.githubusercontent.com/35582033/100476600-015c3a00-30b4-11eb-9788-cbcf8c1ab4be.png)

**Comment by toasted-nutbread** [comment] 2020-11-27 18:51
Duplicate of #1068; fixed by #1069. Queued for [20.11.1.1 patch release](https://github.com/FooSoft/yomichan/issues/980#issuecomment-733785189), whenever FooSoft has time.

**Closed** 2020-12-01 23:39 UTC
Labels: duplicate
